### PR TITLE
Better like this?

### PR DESCRIPTION
**Pull request by nisse3000**

### CODE REVIEW

**Comment by WardLT** [comment]
Looks good to me!

**Comment by computron** [comment]
Thanks!

**Comment by nisse3000** [comment]
@computron and @WardLT, should we also switch over to using lists instead of tuples as return type of feature labels (cf., EwaldEnergy featurizer in structure.py)? I can see people wanting to slightly modify labels in an easy way (not converting tuples to lists). Does that make sense?

**Comment by computron** [comment]
For my standpoint everything should be lists

-features
-feature labels
-citations
-implementors

**Pull request merged**
