### PR TITLE
add partial site stats fingerprint

### PR DESCRIPTION
**Pull request by jacksund**
(original discussion for this request is located on the discourse page [here](https://matsci.org/t/partialssitestatsfingerprint-request/41754))

## Summary

This adds a PartialsSiteStatsFingerprint. 

Much like there is the RDF and partial-RDF fingerprints (partial = broken down by element pairs), this extends the same idea to SiteStats and partial-SiteStats fingerprints (partial = SiteStats broken down by element).

Example use:
``` python
from pymatgen.core import Structure
from matminer.featurizers.structure.sites import PartialsSiteStatsFingerprint

# Using rocksalt NaCl as a test structure
s = Structure(
    lattice=[
        [3.485437, 0.0, 2.012318],
        [1.161812, 3.286101, 2.012318],
        [0.0, 0.0, 4.024635],
    ],
    species=["Na", "Cl"],
    coords=[[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]],
)

# Setup mimics partial-RDF fingerprint
f = PartialsSiteStatsFingerprint.from_preset("CrystalNNFingerprint_cn")
f.fit([s])

# Demo of features
labels = f.feature_labels()
fingerprint = f.featurize(s)
```

### CODE REVIEW

**Comment by ardunn** [comment]
Hi @jacksund thanks for the PR! I am quite busy at the moment but after next week I will be able to do a full review on this and we can start merging it in!

In the meantime, I'll at least authorize the CI to run

**Comment by ardunn** [comment]
@jacksund Oh, and if you can add a unittest when you get the chance that would be awesome!

**Comment by jacksund** [comment]
Awesome, thank you! I'll fix up the linting and add some tests in the meantime

**Comment by jacksund** [comment]
it actually looks like my linting check didn't even run. The issue seems to be with the CI workflow -- perhaps a change in black api is causing it to fail.

**Comment by jacksund** [comment]
Would you be able to update your dev-install and contrib docs at some point too? Just little things to help others:

- For the dev-install, it requires numpy to be installed, so a totally clean environment throws an error:
- For the contrib docs, it wasn't clear how I should run the test suite -- I keep running into issues with optional dependencies like dscribe.

The test suite keeps giving me problems, so I'm uses the CI to run tests for now. Hope that's alright :sweat_smile:

**Comment by jacksund** [comment]
@ardunn I figured out the dev install and the tests should be working for this now. Can you take a look?

**Comment by jacksund** [comment]
@ardunn hey just wanted to check in. Would this PR still be reviewed/accepted?

**Comment by ardunn** [comment]
@jacksund Looks good, thanks for the contribution!

**Comment by jacksund** [comment]
Awesome! Thank you so much for reading through it 😄

**Comment by jacksund** [comment]
fyi my tests passed locally, but I don't think the CI was ever approved to run/check the final commit. If it throws issues in the CI, just let me know and I'll open a new PR to fix it

**Comment by ardunn** [comment]
no problem, I need to fix the matminer tests anyways and I don’t think it’s related to this PR really

Thanks,
Alex

**Pull request merged**
