### PR TITLE
Addition of FractionalAttribute class + appropriate unit testing

### PR DESCRIPTION
**Pull request by aaggarw99**

### CODE REVIEW

**Comment by computron** [comment]
Hi @aaggarw99 

Thanks for the contribution; I am going to hold off on reviewing and pulling this change until I figure out what is going to happen with the base featurizer classes.

**Comment by WardLT** [comment]
Hello @computron ,

@aaggarw99 is an intern at UChicago working with @JFChen3 and I on the refactor. 

I've been iterating with him off screen on these changes.

To cut down on the chaos, should I fork the "featurizer_refactor" branch and only issue pull requests to this repository when they are ready for you to review?

Sorry for the confusion

**Comment by matk86** [comment]
i have restored the featurizer branch to the original PR

**Comment by WardLT** [comment]
I'm closing this pull request. I've talked to @aaggarw99 , and we're going to revise this change based on the restored version of the featurizer branch.

**Pull request closed without merging**
