### PR TITLE
Bit of cleanup/standardization for data retrieval

### PR DESCRIPTION
**Pull request by montoyjh**
In the process of refactoring tutorials, found that there was some inconsistency in the data retrieval tools.  This PR resolves some of that, and includes a bit of cleanup.  The primary thing is that each data retrieval tool has a "get_dataframe" method that interfaces directly to the data retrieval API.  I think there could still be more uniformity on these methods, but that'll have to be a TODO for now.

### CODE REVIEW

**Comment by computron** [comment]
Thanks - would be worth taking a look at the Codacy issues tho. I will fix them after merging

**Comment by WardLT** [comment]
Should we make all of the classes inherit from a single base class? For now, it seems like the main thing the base class would have is the `get_dataframe` abstract method.

**Comment by computron** [comment]
@WardLT Sure

(note the comment is probably best as a new issue referring to the PR, otherwise I have trouble tracking down all "open" things to address)

**Comment by WardLT** [comment]
Cool. I'll open up an issue (now, and in the future)

**Pull request merged**
