### PR TITLE
remove pandas~=1.5 pin

### PR DESCRIPTION
**Pull request by tschaume**
@ml-evs we would like to upgrade to pandas 2 for MP. Would it be possible to remove the `pandas` requirement in matminer?

### CODE REVIEW

**Comment by ml-evs** [comment]
Could you also update it in the pinned ci versions so we know what works/what doesn't? I didn't add the upper bound but presumably something breaks without it

I stalled in my other dep update PR, can't remember if I tried to update pandas there

**Comment by ml-evs** [comment]
> Could you also update it in the pinned ci versions so we know what works/what doesn't? I didn't add the upper bound but presumably something breaks without it
> 
> I stalled in my other dep update PR, can't remember if I tried to update pandas there

Feel free to merge this in the meantime btw

**Comment by tschaume** [comment]
@ml-evs I ran the `upgrade-dependencies` action and merged the update requirements files (see #891).

**Comment by ml-evs** [comment]
Thanks, the issue I had with that PR is that the tests were never actually running in the CI, and several changes were needed to get them to pass in #
can take a look at this again next week if I get time

**Comment by ml-evs** [comment]
@tschaume just back from holiday and have checked this, lots of test failures and some incompatibility with pandas 2 at the moment, have made some changes in #912 but there are still lots of spurious test failures. If matminer is in use at MP would someone be able to take a look at these to accommodate the deps update?

**Comment by tschaume** [comment]
@ml-evs Thanks! We unfortunately don't have any bandwidth to help with the matminer development or maintenance. @ardunn any chance you have some cycles left over to look at this? Thanks!

**Pull request closed without merging**
