### PR TITLE
Add expt_formation_enthalpy_kingsbury and expt_gap_kingsbury datasets

### PR DESCRIPTION
**Pull request by rkingsbury**
## Summary

This PR contains documentation for two new datasets - `expt_formation_enthalpy_kingsbury` and `expt_gap_kingsbury` containing experimental formation enthalpies and bandgaps, respectively. In the formation enthalpy dataset, there are 2,135 unique materials, of which 1,834 include uncertainties and 1,580 have associated mpids. The bandgap dataset is identical to the existing `matbench_expt_gap` dataset, except that 2,481 materials have been associated with mpids and columns have been renamed for consistency with the formation enthalpy data.

## Methods

This dataset is a compliation of experimental formation enthlalpy values for solids, in eV/atom. The original data was compiled by the Materials Project and Matminer teams from multiple sources. 

The majority of the data is derived from the Kubashewski tables, the NIST JANAF tables, and

Kim, G., Meschel, S., Nash, P. et al. Experimental formation enthalpies for intermetallic phases and other inorganic compounds. Sci Data 4, 170162 (2017).  https://doi.org/10.1038/sdata.2017.162.  which is itself a compilation of more than 50 years worth of experimental data. Their complete dataset is available at https://figshare.com/collections/Experimental_formation_enthalpies_for_intermetallic_phases_and_other_inorganic_compounds/3822835 and the columns are explained in detail at https://www.nature.com/articles/sdata2017162/tables/2

Note that I went back to the original Kim et al. data, rather than building on the existing matminer `expt_form_e` dataset, because I wanted to include the uncertainties and compare the mp-ids assigned by Kim et al. to those assigned here. Also, I retained the original references (those cited by Kim et al.) in the DataFrame, rather than just citing the Kim et al. paper.

Ryan Kingsbury, Amanda Wang, and Ayush Gupta assembled, cleaned, and deduplicated this data as documented below. Briefly:
- All elements were excluded
- All gases were excluded
- Formulas with multiple entries were deduplicated by first excluding the Kubashewski value (if there was one) since more recent data are generally considered more reliable. Among the remaining entries, we selected the single value that was closest to the average. If the remaining values differed by more than 0.1 eV/atom, that material was removed from the dataset.

Formulas were matched to a likely Materials Project ID (`likely_mpid`) according to the following procedure:
- The data compiled by Kim et al. contained mpids for many compounds. Although it is not clear exactly what approach these authors used to assign mpids, their data includes spacegroups for many compounds that do not have mpids, suggesting that the reported spacegroups are NOT based on the mpid. 
- As such, for each formula, we compiled candidate mpids that were 1) not marked 'theoretical', 2) matched at least one ICSD material, and 3) were within 200 meV of the DFT-computed energy hull and 4) not deprecated. This was done based on MP database 2021.03.
- We chose the candidate with the lowest `e_above_hull` whose spacegroup matched the reported spacegroup (when available); otherwise we chose the lowest `e_above_hull`

## Validation

I performed a series of spot checks and manual validation steps to verify the integrity of the final dataset. Briefly:

* Any compound that was excluded due to a large range of values (>0.1 eV/atom) was manually inspected. Several typos and data entry errors were caught and corrected this way
* Many `likely_mpids` were checked against the MP database and compared to the mp-ids assigned by Kim et al. In a number of cases the Kim et al. mp-ids were theoretical materials, so a `likely_mpid` was not assigned. In every other case but one, the Kim-assigned mpid matched the `likely_mpid`, and in that one case the Kim et al. mpid was far away from the hull.
* The spacegroups of the `likely_mpid` compounds in the MP database matched the Kim et al. reported spacegroup in every case.
* There are only 9 materials with positive formation energies, and these are consistent with the NIST database.
* There do not appear to be any particular, crazy outliers when comparing experimental and computed formation enthalpies:

image

### CODE REVIEW

**Comment by rkingsbury** [comment]
@ardunn please wait until I give you the go ahead before copying over the .json files for these datasets. Parts of our database are still updating for today's release and I want to regenerate the data one more time after it's all finished to make sure the data is fully consistent with the final release.

**Comment by janosh** [comment]
@rkingsbury Is this dataset downloadable yet? The aleatoric uncertainties make it particularly interesting.

**Comment by rkingsbury** [comment]
> @ardunn please wait until I give you the go ahead before copying over the .json files for these datasets. Parts of our database are still updating for today's release and I want to regenerate the data one more time after it's all finished to make sure the data is fully consistent with the final release.

@ardunn the .json files are ready to go now, at the Google Drive links I emailed to you.

**Comment by ardunn** [comment]
@rkingsbury thanks for this work! Could we rename it though to not include matbench? Just because the matbench datasets adhere to a pretty strict 1-input 1-output format. Maybe just call it `expt_formation_enthalpy_kingsbury` or similar (last name of first author on the publication) for now. Eventually we can incorporate it into the next iteration of matbench proper.

**Comment by rkingsbury** [comment]
> 
> 
> @rkingsbury Is this dataset downloadable yet? The aleatoric uncertainties make it particularly interesting.

@janosh soon! I'll defer to @ardunn on when/how to make it available.

**Comment by rkingsbury** [comment]
> 
> 
> > @ardunn please wait until I give you the go ahead before copying over the .json files for these datasets. Parts of our database are still updating for today's release and I want to regenerate the data one more time after it's all finished to make sure the data is fully consistent with the final release.
> 
> @ardunn the .json files are ready to go now, at the Google Drive links I emailed to you.

FYI @ardunn I made a small addition to the dataset at about 8:30 am this morning (3/24) to add some extra formulas.

**Comment by ardunn** [comment]
ok @rkingsbury I just downloaded the files from Drive today (right now), are those correct? If so I can just merge in and fix the metadata manually, as I need to add the URLs anyways

**Comment by rkingsbury** [comment]
### Dataset

> ok @rkingsbury I just downloaded the files from Drive today (right now), are those correct? If so I can just merge in and fix the metadata manually, as I need to add the URLs anyways

Thanks @ardunn. The files you downloaded should be the most up to date that I've generated. However, there is one item we should discuss, and this is something that I'll defer to you and @mkhorton on. 

In the course of using this dataset, we've identified 8 magnetic materials for which the wrong magnetic ordering is stabilized in database `2021.03.22`. This means that for those eight, the `likely_mpid` is assigned to the _current_ but likely incorrect ground state. We could either 1) leave them as-is (where the `likely_mpid` points to the ground state in the current database) and potentially update the `likely_mpid` against a future database release, or 2) go ahead and assign these 8 `likely_mpid` to what we know to be the correct ground states even though they don't show as such in the existing database.

I don't have a strong feeling one way or another, but I do think we should make a decision about this before you go to the effort to publish this dataset in matminer. Personally, I lean toward updating the 8 `likely_mpid` to point to what we know are the correct ground states, in anticipation of future database releases that may restabilize them.

I have uploaded an alternate version of the dataset that remaps the `likely_mpid` for the 8 compounds to the correct ground state according to the following dictionary, and shared a link with you and @mkhorton. It's called `matbench_expt_formation_enthalpy_magnetic_mpids.json`. It's fine with me if you and Matt move forward with whichever version you think is best.

```
correct_mpids={"Ca(FeO2)2": "mp-1271532",
              "V2O3": "mp-18937",
              "Fe3O4": "mp-19306",
              "LiFeO2": "mp-19419",
              "FeMoO4": "mp-556667",
              "KFeO2": "mp-759749",
              "Ti(FeO2)2": "mp-780585",
              "MoF5": "mvc-3781"}
```

### Naming

> @rkingsbury thanks for this work! Could we rename it though to not include matbench? Just because the matbench datasets adhere to a pretty strict 1-input 1-output format with no extra data included. Maybe just call it 
`expt_formation_enthalpy_kingsbury` or similar (last name of first author on the publication) for now. Eventually we can incorporate it into the next iteration of matbench proper. All the validation data and methods will also be included in the forthcoming matbench version.

Sure, totally up to you if you want to rename it. I initially thought that 'matbench' signified that the dataset had been deduplicated and curated which is why I went with that name, but if you have a different scheme feel free to change it. I'll also note that by adding `likely_mpid` to `matbench_expt_gap`, it sounds like I may have broken that 1:1 mapping rule, so you may want to rename that one too.

The dataset will most likely be described in a paper to be posted on ChemRXiv in the very near future. A working reference and title are:

> Wang, A., Kingsbury, R.S., Horton, M., McDermott, M. Jain, A., Ong, S.P., Dwaraknath, S., and Persson, K. A framework for quantifying uncertainty in DFT energy corrections.

I'll defer to you whether or not you want to add this info to the metadata now or wait until we post the paper. I imagine at the very least we'll need to update the metadata when the paper goes live.

@mkhorton do you have an opinion about an alternate name for the datasets? Specifically, would you want to go with @ardunn 's proposal of using the first author of the paper (e.g. `expt_formation_enthalpy_wang`) or maybe attach something more "organizational" like 'MP' or 'matproj' or something to signify that we intend for these datasets to be broadly useful, not just for a single purpose or paper?

Again, I'm happy for you to proceed with whatever name you and Matt decide is best.

Thanks for your help integrating this!

**Comment by mkhorton** [comment]
> Specifically, would you want to go with @ardunn 's proposal of using the first author of the paper (e.g. expt_formation_enthalpy_wang) or maybe attach something more "organizational" like 'MP' or 'matproj' or something to signify that we intend for these datasets to be broadly useful, not just for a single purpose or paper?

Apologies for late response to this. No opinion on the name honestly! Any data that _originates_ from MP should be clearly branded as such but that's not the case here. I would err towards a name that acknowledges the original compilers of the data if that wasn't unwieldy.

**Comment by ardunn** [comment]
@rkingsbury @mkhorton here is what I will do. We will use the corrected mapping for those 8 compounds, so the file that will be uploaded is `matbench_expt_formation_enthalpy_magnetic_mpids.json`. I will add a "notes" column and will add a note clarifying each of those compounds so that anyone looking at the data understands the situation. More, I'll add some additional metadata to clarify the situation. The datasets will be suffixed with `_wang`.

**Comment by rkingsbury** [comment]
Thanks @ardunn. Could we pause this for another ~1 week? Apologies for the false start. We're having an internal discussion about an alternate way of deduplicating the data (perhaps preferring data that has uncertainties, even if it's older) that could result in me changing a few numbers slightly. I'd rather delay now and truly finalize this dataset than have to send iterative updates right after you go to the effort of integrating into matminer.

**Comment by ardunn** [comment]
sure! ping me again when it's ready and shoot me the final json on email. I'll merge and update the rest as needed once you've decided on a final form for the data.

**Comment by rkingsbury** [comment]
## UPDATE 2021-04-15

I have revised the formation enthalpy dataset using a more comprehensive set of source data, a more rigorous deduplication procedure, and more manual checking / adjustment of selected mpid values.

* Detailed procedures for how this data were compiled are given in the attached screenshots, which are from a forthcoming manuscript
* I used the same procedure described in the last paragraph to assign `likely_mpid` to the bandgap data
* Updated validation of the experimental values against computed values from the MP database (by matching the `likely_mpid` are shown following the methods


## Action Requested

Both datasets are final and ready to integrate into matminer. I have updated the .json descriptions in this PR and emailed final .json files to @ardunn . Please let me know if anything else is needed.



image
image

image

image

**Comment by ardunn** [comment]
@rkingsbury the `bibtex_refs` are just a bibtex formatted version of all the references that went into making the dataset. Ie., the things you'd like a user of the dataset to cite if they use the data. This should include all the methods papers and can also include the papers for the raw data as well. 

The `reference` section is kind of just like single authoritative reference. So if someone doesn't want to comb thru the bibtex refs but wants to get an idea of where this version of the data came from, they can use that. 

These aren't strictly enforced or anything, but just recommendations!

**Comment by rkingsbury** [comment]
> @rkingsbury the `bibtex_refs` are just a bibtex formatted version of all the references that went into making the dataset. Ie., the things you'd like a user of the dataset to cite if they use the data. This should include all the methods papers and can also include the papers for the raw data as well.
> 
> The `reference` section is kind of just like single authoritative reference. So if someone doesn't want to comb thru the bibtex refs but wants to get an idea of where this version of the data came from, they can use that.
> 
> These aren't strictly enforced or anything, but just recommendations!

Thanks @ardunn , I made a few adjustments to the references based on this. It looks like I introduced one linting issue at line 782 that I can't figure out. If you see how to fix it, would you mind taking care of it? 

Aside from that, no other questions from me. Feel free to merge when ready!

**Comment by rkingsbury** [comment]
Hi @ardunn , do you need anything else from my side on this?

**Comment by rkingsbury** [comment]
FYI, I've updated the metadata with the link to our preprint manuscript, which has just been posted.

**Comment by ardunn** [comment]
@rkingsbury merged, files will be available for download momentarily

**Comment by ardunn** [comment]
And some quick notes:
- Raw file for formation enthalpy is available here: https://ndownloader.figshare.com/files/28232538, page is: https://figshare.com/articles/dataset/expt_formation_enthalpy_kingsbury/14701143
- Raw file for expt gaps is here: https://ndownloader.figshare.com/files/28232598, page is: https://figshare.com/articles/dataset/expt_gap_kingsbury/14701146
- url on `expt_formation_enthalpy_kingsbury` was removed and appended to the reference. The `url` field is the url for downloading the file (ie, from figshare), not for reference (no problemo tho)

Tested locally right now, working ok:

```
df = load_dataset("expt_gap_kingsbury")
Fetching expt_gap_kingsbury.json.gz from https://ndownloader.figshare.com/files/28232598 to /Users/ardunn/alex/lbl/projects/common_env/dev_codes/matminer/matminer/datasets/expt_gap_kingsbury.json.gz
df
Out[9]: 
     likely_mpid  expt_gap            formula
0           None      0.00           Ag(AuS)2
1       mp-29717      0.00         Ag(W3Br7)2
2           None      1.83   Ag0.5Ge1Pb1.75S4
3           None      1.51  Ag0.5Ge1Pb1.75Se4
4           None      0.00             Ag2BBr
          ...       ...                ...
4599        None      1.72             ZrTaN3
4600     mp-1539      0.00               ZrTe
4601        None      0.00             ZrTi2O
4602    mp-16548      0.00             ZrTiF6
4603      mp-675      0.00               ZrW2
[4604 rows x 3 columns]
df = load_dataset("expt_formation_enthalpy_kingsbury")
df
Out[11]: 
     formula  ...  likely_mpid
0     Ag2CO3  ...      mp-4691
2       Ag2O  ...       mp-353
3      Ag2O3  ...    mp-546190
4       Ag2S  ...    mp-610517
5     Ag2SO4  ...      mp-5625
      ...  ...          ...
2592   CaCl2  ...     mp-23214
2593   Al2O3  ...      mp-1143
2596    GaF3  ...       mp-588
2597    InF3  ...      mp-6949
2599    Cs2O  ...      mp-7988
[2135 rows x 6 columns]
```

**Comment by rkingsbury** [comment]
Thanks @ardunn !

**Pull request merged**
