### PR TITLE
Added a 'BagofBonds' Featurizer

### PR DESCRIPTION
**Pull request by ardunn**
- Addresses #97 

- __For a single structure:__
Returns the fraction of each kind of bond combination, based on a pymatgen `NearNeighbors` method

- __For a dataframe of structures:__
Returns the 'unified' list of all bond fractions, concatenated from the bonds present in each structure. Bonds present in the unified list but not in an individual structure (e.g., no C-C bond in CsCl) are represented as NaN:

For example, on a dataframe containing the `diamond_no_oxi`, `ni3al`, and `cscl` structures from `test_structures.py`:
```python
bf = BondFractions.from_preset("MinimumDistanceNN")
bf.featurize_dataframe(df, 'structure')
```
```
>>>
  composition            structure  C-C bond frac.  Al-Ni bond frac.  Al-Al bond frac.  Ni-Ni bond frac.  Cl--Cs+ bond frac.  Cl--Cl- bond frac.  Cs+-Cs+ bond frac.
0         (C)  [[2.554, 1.806, ...             1.0               NaN               NaN               NaN                 NaN                 NaN                 NaN
1    (Al, Ni)  [[0. 0. 0.] Al, ...             NaN               0.5               0.0               0.5                 NaN                 NaN                 NaN
2  (Cl-, Cs+)  [[2.105, 2.105, ...             NaN               NaN               NaN               NaN                 1.0                 0.0                 0.0

```

Alternatively, the `NaN` values can be replaced during featurization with a 'bad bond value' (`bbv`, open to name changes),  an argument/attribute of BondFractions.

```python
bf.bbv = 0.0
bf.featurize_dataframe(df, 'structure', inplace=True)
```
```
>>>
  composition            structure  C-C bond frac.  Al-Ni bond frac.  Al-Al bond frac.  Ni-Ni bond frac.  Cl--Cs+ bond frac.  Cl--Cl- bond frac.  Cs+-Cs+ bond frac.
0         (C)  [[2.554, 1.806, ...             1.0               0.0               0.0               0.0                 0.0                 0.0                 0.0
1    (Al, Ni)  [[0. 0. 0.] Al, ...             0.0               0.5               0.0               0.5                 0.0                 0.0                 0.0
2  (Cl-, Cs+)  [[2.105, 2.105, ...             0.0               0.0               0.0               0.0                 1.0                 0.0                 0.0

```
- Citation is this paper [http://pubs.acs.org/doi/ipdf/10.1021/acs.jpclett.5b00831](url) although the concept here is simpler than what they do. Considering they coined the `BagofBonds` term with the same concept though we should probably cite them.

- Was unsure how to proceed on hashing the bond fractions as mentioned in #97 so that is not included in this PR.

### CODE REVIEW

**Comment by computron** [comment]
why add ``crystal_system_int``?

One can use pandas to get the data as ints:

http://benalexkeen.com/mapping-categorical-data-in-pandas/

Plus for some models like linear regression, having them as strings allows you to call the get_dummies function which lets you do a one-hot encoding matrix of vars

So I think if someone really wants to get the categories as ints they can use pandas to convert. That way matminer doesn't need to duplicate the info as string and int in every single featurizer that returns a categorical var.

If you think it would be helpful to put some of the code in that link in matminer for reference, you could put it in the ``utils/conversions.py`` module to help people convert from string to int or string to dummy-matrix

**Comment by ardunn** [comment]
@computron I do not think that is a part of the code I added?  The changes I see regarding `crystal_system_int` is just a Pycharm PEP8 auto-reformatting added it on a new line. The only new code is in BagofBonds, the rest of the changes in structure.py are PEP8 reformatting. 

Or if you mean something else, could you clarify?

**Comment by computron** [comment]
Ah I see, OK I was just looking at the changes very quickly

Note: you don't need to change code to make Codacy happy. It's there for suggestions only.

**Comment by computron** [comment]
Side note: I remembered why I added ``crystal_system_int``. It's because you can assign a real order to the crystal system in terms of increasing or decreasing symmetry. So they are not just dummy indices for each category, there is a specific order of crystal systems

**Pull request merged**
