### PR TITLE
add triangle, a "phase-diagram-type" plot, support + setup_labels to help preparing labels for all plots

### PR DESCRIPTION
**Pull request by albalu**
## Summary

* a simple triangle plot is added + tests
* defined setup_labels and used in xy and triangle

## TODO

some todos are added which both add functionality (sizes in triangle or pyramid plots) and help cleanup figrecipes

### CODE REVIEW

**Comment by ardunn** [comment]
I can't seem to get it to work...for example try this:

```
df = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6], 'z': [7, 8, 9], "my labels":["pt1", "coolpt", "badpt"]})
pf = PlotlyFig()
pf.triangle(data=df, cols=['x', 'y', 'z'], labels='my labels')
```

Is the input format of my data incorrect?

**Comment by albalu** [comment]
What do you get? See the test. I have other examples too. This is most
appropriate for data with rows summing up to the same number (e.g
percentage)

On Jun 9, 2018 8:12 PM, "Alex Dunn" <notifications@github.com> wrote:

I can't seem to get it to work...for example try this:

df = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6], 'z': [7, 8, 9], "my
labels":["pt1", "coolpt", "badpt"]})
pf = PlotlyFig()
pf.triangle(data=df, cols=['x', 'y', 'z'], labels='my labels')

Is the input format of my data incorrect?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hackingmaterials/matminer/pull/251#issuecomment-396008256>,
or mute the thread

**Comment by ardunn** [comment]
I ran the code in the test fine, but when I do:

```
df = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6], 'z': [7, 8, 9], "my labels":["pt1", "coolpt", "badpt"]})
pf = PlotlyFig()
pf.triangle(data=df, cols=['x', 'y', 'z'], labels='my labels')
```

I got 
```
Traceback (most recent call last):
  File "plot.py", line 1625, in <module>
    pf.triangle(data=df, cols=['x', 'y', 'z'], labels='my labels')
  File "plot.py", line 1553, in triangle
    raise ValueError('triangle plot requires 3 and only 3 columns!')
ValueError: triangle plot requires 3 and only 3 columns!
```

**Comment by albalu** [comment]
@ardunn , that was a bug. Thanks for catching it! This simple version should be ok for now. There are quite a few todos that I'll take care of when I come back.

**Comment by ardunn** [comment]
Ok sounds good. I am using plotlyfig a lot recently and I am catching a lot of new errors. I think I will submit a new issue which lists them. They're mostly minor though

**Comment by computron** [comment]
merging for now, @ardunn please submit issues when you see them

**Pull request merged**
