### PR TITLE
minor bugfix: set accuracy to int, None is not accepted.

### PR DESCRIPTION
**Pull request by albalu**
I set it to 12 that is the default for acc_factor in pymatgen's EwaldSummation.

### CODE REVIEW

**Comment by computron** [comment]
@WardLT does this class need an ``accuracy`` parameter at all?

I would guess that the default (12 decimal places) is not really worth fiddling with, have you found otherwise?

**Comment by computron** [comment]
Is 12 the number you'd set as default?

**Comment by WardLT** [comment]
I suspect 12 is unnecessarily accurate. Maybe 4 could be a better default? I use an accuracy of 4 without seeing too much noise in the forces from Ewald summation.

**Comment by computron** [comment]
@albalu I would suggest making the default either 4 or 5 in this PR

**Comment by computron** [comment]
Thanks!

**Pull request merged**
