### PR TITLE
strictly checking feature_labels vs. current labels to avoid overwritting

### PR DESCRIPTION
**Pull request by albalu**
This is to address the first 2 parts of #127 . Some new tests had to be updated.

### CODE REVIEW

**Comment by ardunn** [comment]
Why is BoB test being updated?

**Comment by albalu** [comment]
"restart df to avoid overwriting features" to avoid the error cause by new name checking I added

**Comment by albalu** [comment]
strange: locally test_chemicalSRO in test_site.py fails for me but not here. Anyone else experience the same thing? @Qi-max ?

**Comment by Qi-max** [comment]
eh, the test passes when submitted yesterday, double check ing...

**Comment by Qi-max** [comment]
Understood. This is due to the new modification of featurize_dataframe, which call feature_labels before featurize (previously the sequence is reversed), but my label contains the elements name in the structure that can not be determined beforehand.

**Pull request merged**
