### PR TITLE
Added cluster packing efficiency attributes

### PR DESCRIPTION
**Pull request by WardLT**
Added features related to the cluster packing efficiency model of [Laws et al.](http://www.nature.com/doifinder/10.1038/ncomms9123)

These are some of the features used in a recent paper by [Ren et al.](http://advances.sciencemag.org/content/4/4/eaaq1566)

Sorry for the extra changes. I did not realize until after I committed that I ran "reformat" code on the whole file, which ensured that no lines are longer than the specified maximum. Would you like me to go and change those lines back?

### CODE REVIEW

**Comment by computron** [comment]
For the reformat, it's generally better to do as a separate commit but we can work with it. I'd just make sure that any auto-reformat is readable, sometimes it can make things worse and a manual reformat is needed.

**Comment by computron** [comment]
Also a note that I typically prefer a 100 char max line length (against PEP guidelines) but don't have a strong preference for 80 vs 100 so long as it's in the interest of code readability.

**Comment by WardLT** [comment]
I'll set my editor to 100. I try to avoid running it on the whole file, I just happened to miss it this time (if I don't highlight text when calling re-format, it runs the whole file rather than my highlight).

The changes do affect readability, IMO. I'm currently reverting them.

**Comment by WardLT** [comment]
Alright, I got rid of the most ugly changes. I'll be more careful next time.

**Comment by computron** [comment]
Thanks!

**Pull request merged**
