### PR TITLE
BagofBonds update

### PR DESCRIPTION
**Pull request by ardunn**
## Summary
- Performance improvements
- Made BoB presets better as mentioned in #128 
- Added `allowed_bonds` in BoB
- Added `approx_bonds` in BoB
- originally brought up in #127 

## Details
- Define `allowed_bonds` to limit the kinds of bonds which can be returned. If a structure has a forbidden bond, skips it and returns all other bonds normally (including bad bond values, where the forbidden list has bonds the structure being featurized does not). This can result in some rows having bond fractions summing to less than 1. 

- Allowed bonds can be defined by the list of feature labels a BoB object returns after featurization (`bob.feature_labels()`)

- If you do not want `allowed_bonds` to skip forbidden bonds, set `approx_bonds` to true to approximate forbidden bonds with chemically similar bonds found in `allowed_bonds`. Chemically similar bonds are determined by finding the bond in `allowed_bonds` with the smallest "distance" to the forbidden bond. Approximate bonds with equal distances to the forbidden bond divide the bond fraction equally among them. 

- The "distance" between bonds is determined by converting each bond into a 2-tuple of mendeleev numbers (MN) from their species, so each bond gets an (x,y) coordinate in MN space. A bond's x and y are swapped automatically if necessary (ie if we are comparing (O-Li bond) and (Na-O bond), making sure we calculate the MN distance between (Li and Na) and (O and O), _not_ (Li and O) and (O and Na)). Then the distance between (x1, y1) and (x2, y2) is Euclidean. 

## Examples
Get dataframe of some Na-O and Li-O compounds
```python
df = mpr.get_dataframe(criteria={"material_id": {"$in": ['mp-1960', 'mp-841', 'mp-1018789', 'mp-2352', 'mp-1901']}}, properties=['structure', 'spacegroup.number', 'pretty_formula'])
```
Featurize only the LiO compounds, for training:
```python
bob = BagofBonds.from_preset("MinimumDistanceNN")
print(bob.featurize_dataframe(df.iloc[[0, 2, 4]], 'structure'))
```
```
                                                     structure  spacegroup.number pretty_formula  Li - Li bond frac.  Li - O bond frac.  O - O bond frac.
material_id                                                                                                                                              
mp-1018789   {'lattice': {'a': 3.98566942, 'c': 2.96110099,...                 58           LiO2                 0.0           0.750000          0.250000
mp-1960      {'lattice': {'a': 3.291071792359756, 'c': 3.29...                225           Li2O                 0.0           1.000000          0.000000
mp-841       {'lattice': {'a': 3.18036198, 'c': 7.70352187,...                194          Li2O2                 0.0           0.857143          0.142857
```
Set the allowed bonds to the feature_labels of the previous featurization. Featurize the dataframe allowing only bonds containing Li and O, say, for testing:
```python
allowed = bob.feature_labels()
bob.allowed_bonds = allowed
print(bob.featurize_dataframe(df.iloc[[1, 3]], 'structure'))
```
```
                                                     structure  spacegroup.number pretty_formula  Li - Li bond frac.  Li - O bond frac.  O - O bond frac.
material_id                                                                                                                                              
mp-1901      {'lattice': {'a': 3.47402655, 'c': 5.67466155,...                 58           NaO2                 NaN                NaN              0.25
mp-2352      {'lattice': {'a': 3.9563243674727504, 'c': 3.9...                225           Na2O                 NaN                NaN              0.00
```
The Na-O and Na-Na bonds were skipped, because they was not in allowed_bonds. The `NaN` values are the bad_bond_values, which can be set with `bob.bbv`. 
If we do not want the Na-O and Na-Na bonds skipped, use `approx_bonds` to approximate these bonds with their most chemically similar, Li-O and Li-Li. 
```python
bob.approx_bonds = True
print(bob.featurize_dataframe(df.iloc[[1, 3]], 'structure'))
```
```
                                                     structure  spacegroup.number pretty_formula  Li - Li bond frac.  Li - O bond frac.  O - O bond frac.
material_id                                                                                                                                              
mp-1901      {'lattice': {'a': 3.47402655, 'c': 5.67466155,...                 58           NaO2                 0.0               0.75              0.25
mp-2352      {'lattice': {'a': 3.9563243674727504, 'c': 3.9...                225           Na2O                 0.0               1.00              0.00
```

### CODE REVIEW

**Comment by computron** [comment]
Thanks!

Some comments:
- The way the featurizer is intended to work with most models, probably for most cases you want the "bad bond value" to just be zero, not NaN. i.e., there is no Li-Li bond component to Na2O. It doesn't matter that it's not possible to have that component.
- If you define the element order in the bond in order of Mendeelev number (lowest element Mendeleev number first, highest Mendeelev number second), I think you can have a consistent bond label (no "Li-O" vs "O-Li") *plus* not need to check multiple combinations for distance (just take the direct distance).

A more general comment is that multiple of these featurizers require knowing in advance all the entries of the dataframe in order to determine the feature columns. It might be better to look at the ``fit_transform`` methods in scikit-learn often used for text mining as an inspiration rather than trying to cram things into the current Featurizer format. I'll submit a separate issue about this, just mentioning it here.

**Comment by ardunn** [comment]
@computron Both the bulleted comments have been addressed with the latest commits.

One possible workaround for BoB for the more general comment is to make `enumerate_bonds` and `enumerate_all_bonds` static methods or utility functions. Then there would be no need for overriding `featurize_dataframe`, if a list of bonds was passed into BoB's constructor as a required argument:


```python
bonds_list = BagofBonds.enumerate_all_bonds(structure_list)
bob = BagofBonds(bonds_list, nn=VoronoiNN())
bob.featurize_dataframe(df, 'structures') # featurizes according to bonds_list
```

However this kind of adds an extra step to the usage of the featurizer.

**Comment by computron** [comment]
Merging although we might still need to redo later

Note that you shouldn't change the operation of Featurizer(). Once you have a contract, you should stick to it - otherwise, don't have a contract. We can define a different contract for things that require pre-processing, but we shouldn't violate expectations for a given contract.

**Comment by ardunn** [comment]
Sure, however I don't think any implementation of BoB will change the operation of Featurizer. I was suggesting that if we wanted to avoid the issues in #135 , we could require that a BoB object is created from a list of the desired bonds passed as an argument to the constructor. Having a function to create such a list could be done by moving BoB's `enumerate_all_bonds` to `utils`.  Then when a BoB object is created, it's feature labels are 100% set before any featurization and there will be no `super()` nonsense or bad `feature_labels` calls. This seems like the most logical solution to me (at least for BoB).

**Pull request merged**
