### PR TITLE
Infer compression type in store_dataframe_as_json

### LINKED ISSUE #741: store_dataframe_as_json infer compression from filename
Could we make `store_dataframe_as_json` infer the compression keyword arg from the filename is not explicitly specified?

```py
def store_dataframe_as_json(dataframe, filename, compression=None, orient="split", pbar=True):

    if filename.endswith(".gz") or filename.endswith(".bz2"):  # new
        compression = filename.split(".")[-1]  # new

    if compression not in ["gz", "bz2", None]:
        raise ValueError("Supported compression formats are 'gz' and 'bz2'.")

    if compression and not filename.lower().endswith(".{}".format(compression)):
        filename = "{}.{}".format(filename, compression)
```

### PR DESCRIPTION
**Pull request by janosh**
Closes #741.

I added a new test case for this feature. Could also include a test for this functionality in one of the existing cases to avoid increasing CI run time if you prefer.

### CODE REVIEW

**Comment by janosh** [comment]
@ardunn Could you take a look at this?

**Comment by ardunn** [comment]
lgtm thanks @janosh !

**Comment by janosh** [comment]
Any chance to cut a new version soon? Last one from Aug 2021.

**Comment by ardunn** [comment]
@janosh I'll ping @computron here, should be doable now that the requirements have been updated and a few major issues have been fixed wrt. multiprocessing, oxid states, etc.

**Pull request merged**
