### PR TITLE
Add JARVIS Descriptors, + a few random things

### PR DESCRIPTION
**Pull request by ardunn**
## Summary

* Add the JARVIS CFID descriptors into a new Featurizer, `JarvisCFID`, which takes a structure and outputs anywhere from 4-1557 features (depending on init args). Implementation was based heavily on [the nist implementation](https://github.com/usnistgov/jarvis), with some major revisions to make the code clearer. Two reference json files are needed for `JarvisCFID` to work, and they are found in (edit) the same utils directory as the ElementProperty and MagPie data
* Add a simple test for this new featurizer
* Fix the doc string for a few featurizers which was causing the Table of Featurizers in the docs not to display the description
* an autoreformat of structure featurizers

## TODO (if any)
Docs should be regenerated either in this PR or soon after.

### CODE REVIEW

**Comment by ardunn** [comment]
Closes #280

**Comment by ardunn** [comment]
@WardLT you're right It's been moved :)

**Comment by computron** [comment]
@ardunn FYI I am going to add Kamal as an implementor after pulling your request, as I believe a lot of the code was adapted from what he sent you regarding Jarvis

**Comment by ardunn** [comment]
@computron kk sounds good

**Pull request merged**
