### PR TITLE
Added a class for running multiple featurizers 

### PR DESCRIPTION
**Pull request by WardLT**
The main use case for this class is when featurizers are used in a different application. This way, that application need not write functions that loop over all featurizers in a list or set or have logic that is different for when a user passes a single featurizer or a list of featurizers.

### CODE REVIEW

**Comment by WardLT** [comment]
It seems like the 'unused variable' errors in Codacy are false, and a bug in pylint (see [here](https://github.com/PyCQA/pylint/issues/1609)). Do you agree?

**Comment by computron** [comment]
* don't worry about Codacy
* can you modify so that citations() and implementors() so that you don't get repeated entries (e.g., the same implementors or the same papers multiple times?) e.g. you can make it as a set and then convert to list at the end

**Comment by WardLT** [comment]
`citations` and `implementors` do eliminate repeated entries.

**Comment by computron** [comment]
Strange, I missed it the first time - nevermind!

**Pull request merged**
