### PR TITLE
Moved the SOAP featurizer from matminer.featurizers.structure to matm…

### PR DESCRIPTION
**Pull request by lauri-codes**
…iner.featurizers.site. Also improved the interface and added proper labels.

## Summary

* Moved the SOAP featurizer from matminer.featurizers.structure to matminer.featurizers.site. This makes sense since SOAP is inherently a local descriptor.
* If a user wants to describe a full structure, they should use e.g. SiteStatsFingerprint or roll their own custom kernel for comparing structures.
* Uses the latest DScribe interface 0.2.9.
* Support for almost all DScribe parameters (expect "sparse", since sparse matrices not supported).
* Updated SOAP regression test. The test is however quite primitive...

## TODO (if any)

* I'm not too familiar with how the matminer interface works, and what kind of tests should be performed. I only checked that the constructor, fit(), feature_labels(), and featurize() worked with very simple input. Could someone check that this implementation works as it should and that the code style is OK?

### CODE REVIEW

**Comment by ardunn** [comment]
Hey @lauri-codes thanks for the PR! 

The current matminer implementation looks good to me. I have two higher level questions though:

1. What do you think is the best way of making the SOAP site featurizer a structure featurizer? We currently have a SiteStatsFeaturizer which takes statistics over the features created for each site (e.g., mean, so an example feature might be `"mean Z=11,Z'=14,l=3,n=1,n'=2"` averaged over all the sites in the structure. Do you see this as being a useful way to convert the site features into structure features?

2. We want to make sure the default implementation will give decent results for the intended purposes (e.g., predicting formation energies). Given the defaults for the featurizer are not specified, I could imagine it is hard for someone who is not familiar with SOAP to pick reasonable values for their problem. Do you have any recommended defaults or perhaps a heuristic for picking good values (apart from going through the heavy math on the original papers)?

Thanks!

**Comment by ardunn** [comment]
closes #420

**Comment by lauri-codes** [comment]
Hi @ardunn,

1. I cannot really say what the best way would be, as it depends on the ML method one is using. If you want to stay agnostic with respect to the ML method, averaging done with SiteStatsFeaturizer is perfectly reasonable. It is also what we did when using SOAP to predict formation energies.

2. The values that we used for the DScribe paper for formation energy prediction are available in the supplementary info. If you want, I can dig them up for you. I would hesitate to use them as default values, but providing them under the `from_preset`-function sounds good.

**Comment by ardunn** [comment]
@utf what would you think about the following:

1. merging this PR
2. adding a from_preset SOAP option to SiteStatsFeaturizer
3. Adding a SOAP from_preset option from the default values @lauri-codes referenced

?
I can help do these things 

@lauri-codes if you have good presets for those values, that would be awesome! We could even have multiple from_preset methods based on use case. If you have 2-3 common ones that would be perfect.

**Comment by utf** [comment]
@ardunn This plan sounds sensible to me.

**Comment by ardunn** [comment]
Great! @lauri-codes if you can commit the parameters as `from_preset` methods here that would be ideal. Then I will go about merging this PR and adding a structural featurizer.

**Comment by ardunn** [comment]
Hey @lauri-codes any update on the from_preset implementation? I'd be glad to add it myself but not sure which parameters would be best.

**Comment by lauri-codes** [comment]
Sorry for being inactive on this. I can't right now add the functionality myself, but here are the presets we used in https://doi.org/10.1016/j.cpc.2019.106949):

Preset 1: Formation energy prediction for inorganic crystal structures:
- `r_cut`: 6 (Angstrom)
- `sigma`: 0.4
- `rbf`: "gto"
- `n_max`: 8
- `l_max`: 8
- `crossover`: True
- `periodic`: True

Presets 2-6: Charge prediction for small organic molecules (r_cut and sigma are different for each species): `rbf`: "gto", `n_max`: 8, `l_max`: 8, `crossover`: True, `periodic`: False
- C:
    - `r_cut`: 4 (Angstrom)
    - `sigma`: 0.1
- H:
    - `r_cut`: 8 (Angstrom)
    - `sigma`: 0.05
- O:
    - `r_cut`: 4 (Angstrom)
    - `sigma`: 0.05
- N:
    - `r_cut`: 4 (Angstrom)
    - `sigma`: 0.05
- F:
    - `r_cut`: 6 (Angstrom)
    - `sigma`: 0.1

**Comment by ardunn** [comment]
Great, thanks @lauri-codes ! just saw your update, and very much appreciate your work on this. I will integrate these now.

**Pull request merged**
