### PR TITLE
Improvements to basefeaturizer (+pbar)

### PR DESCRIPTION
**Pull request by ardunn**
## Summary

Add a progress bar, fix a few minor BaseFeaturizer issues

####  Progress bar
* Added a `tqdm` progress bar (`pbar`)for single featurizers and multiplefeaturizers
* Works with featurize_many, featurize_dataframe, and fit_featurize_dataframe
* Progress bar enabled by default
* To my knowledge, works with all valid combinations of arguments to all `*_featurize_*` methods

#### Other
* Changed input signatures of featurize_dataframe for MultipleFeaturizer + FunctionFeaturizer to prevent future errors when args/kwargs added to BaseFeaturizer
* Fixed common return_errors bug which occurred when a featurizer returned a numpy array rather than a list
* Moved a print statement routed to stderr to a warning statement
* Reformatted base.py
* Removed `FunctionFeaturizer` need to overload featurize_dataframe

# Example
```
df = load_elastic_tensor().iloc[:100]
bf = BondFractions()
xrd = XRDPowderPattern()
de = DensityFeatures()
mf = MultipleFeaturizer([bf, de, xrd])
mf.fit_featurize_dataframe(df, "structure", multiindex=True, pbar=True)
```

Output:
```
BondFractions: 100%|██████████| 100/100 [00:09<00:00, 10.52it/s]
DensityFeatures: 100%|██████████| 100/100 [00:00<00:00, 628.06it/s]
XRDPowderPattern: 100%|██████████| 100/100 [00:07<00:00, 14.23it/s]
```

### CODE REVIEW

**Comment by ardunn** [comment]
Closes #273

**Comment by ardunn** [comment]
The difference in parameters Codacy mentions is intentional

**Comment by WardLT** [comment]
This looks very cool! 

A comment not completely related to this PR: A call to the `super` of `featurize_dataframe` was removed by a previous commit [link](https://github.com/ardunn/matminer/commit/269fa53885f0fee37f5ba14a980f84dbdfa7bb45), which prevents the caching operations for VoronoiNN from working. If re-add the call to `super`, we loose the nice progress list for which featurizer is being run but get the caching back. But, do you think that's a worthwhile tradeoff? [I'm in favor in putting it back, but am not sure why the call to super was removed and don't know what other problems it was causing]

**Comment by ardunn** [comment]
Yes that makes sense. 

But how many features overload featurize_dataframe? To me it appears only FunctionFeaturizer does it, and (at a glance) it looks like it could be converted over to _not_ overriding featurize_dataframe.

**Comment by computron** [comment]
@ardunn 

You should do  the doctrings properly (PyCharm can help auto-generate them), not just put a comment that says "same things as before". Meaning, each variable should have its own entry in the "Args" key.

**Pull request merged**
