### PR TITLE
minor: pymatgen version req update

### PR DESCRIPTION
**Pull request by albalu**
## Summary

minor: pymatgen version req update

### CODE REVIEW

**Comment by albalu** [comment]
"Traceback (most recent call last):
  File "/home/circleci/matminer/matminer/featurizers/tests/test_site.py", line 161, in test_crystal_site_fingerprint
    'body-centered cubic CN_8')], 0.5329344, places=7)
AssertionError: 0.5329347060148737 != 0.5329344 within 7 places"

@nisse3000 , is it safe to change this test to places=5 or something subtle is going on?

**Comment by albalu** [comment]
ready to merge.

**Comment by ardunn** [comment]
Why are the number of decimal places fewer than before? A change in pymatgen static data or...?

**Comment by albalu** [comment]
we are not sure but 4 is ok.

**Comment by ardunn** [comment]
ok

**Pull request merged**
