### PR TITLE
Orbital Field Matrix Update

### PR DESCRIPTION
**Pull request by kylebystrom**
Small pull request for the updated orbital field matrix based on my summer project, which takes into account the periods of elements.  I haven't added myself to the citations for this method because I have nothing to cite, but if I'm lucky I might be able to get the improvements into an undergrad journal and add a citation then.

I will start the MBTR wrapper next week.

### CODE REVIEW

**Comment by computron** [comment]
Thanks! Can you just set the default period_tag to False? Then the default implementation will be in-line w/the original orbital field matrix paper.

**Comment by kylebystrom** [comment]
Sure thing. I noticed that both Coulomb matrices also have a default setting that is different from the paper they are based on, should I fix that too?

**Comment by computron** [comment]
Hi Kyle, I think it would be nice for default settings to match their respective papers globally. If there is a particular combination of parameters (or even a single parameter choice) that you think matminer should advocate and that is different than the paper defaults, feel free to add a from_preset() function like in the ElementProperty featurizer. Then one can do something like "OrbitalFieldMatrix.from_preset("matminer")" and get your recommended parameter settings

**Comment by kylebystrom** [comment]
All fixed! Looks like a few checks are queued, but should be good other than that.

**Comment by computron** [comment]
Thanks!

**Pull request merged**
