### PR TITLE
Added a feature table/summary to docs + regen docs

### PR DESCRIPTION
**Pull request by ardunn**
## Summary
- Added script matminer/utils/featurizer_summary.py called by `invoke make-doc` to automatically generate featurizer table. This will account for any new BaseFeaturizer subclasses added to any existing featurizer module. _If new featurizer modules are added to matminer, this file will need to be updated by importing the new module and adding it's high level description in featurizer_summary.py._
- Added feature table/summary to a new page in docs
- Put link to featurizer page on main (index) page
- Added a featurization graphic bc index.rst was text heavy
- Regenerated sphinx docs to include all new featurizers (incl. new structure ones @WardLT wrote, + new BoB)
- Added suitable first line descriptions to each featurizer. 
- Added guideline for writing new featurizer docs. The first line of a new featurizer doc has to be a short, high-level description of the featurizer for this script to work correctly. 
- Added elastic dataset static html to embed in index. It's interactive in the webpage, which is nice.
 
## Screenshots
image
image
image

## Notes
Clicking on the [more] links to the module page as per @computron suggestion
image

### CODE REVIEW

**Comment by ardunn** [comment]
Also added the elastic dataset Figrecipes example in interactive form to the docs via RST iframe. 
Here is screenshot:

image

**Comment by ardunn** [comment]
Closes #193

**Comment by WardLT** [comment]
I think this looks pretty sharp! 

Specially, I like that the table will automatically rebuild with the new documentation (if I understand Sphinx right), that the table links to detailed documentation, abd that you've updated the BaseFeaturizer documentation guide. 

The interactive plot is also a nice addition to the webpage.

One question: Should we move the table generation script to the `doc` folder? It seems a little out-of-place in the main module, since it will likely never be called by users.

**Comment by ardunn** [comment]
@WardLT sure, that makes more sense logistically.

**Comment by computron** [comment]
I know there are some other Featurizers up in the air right now, but I don't want to wait for those to merge this. We'll need to update the docs from time to time anyway

**Pull request merged**
