### PR TITLE
updates

### PR DESCRIPTION
**Pull request by matk86**
* refactor and add unittests for get_pymatgen_descriptor: addresses issue #18 
* py3 compatibilty
* bug fixes
* some formatting fixes

TODO:

* refactor and cleanup the rest
* add tests

### CODE REVIEW

**Comment by computron** [comment]
@matk86 Thanks but we should have talked before these changes. Logan Ward and his colleague are working on a major refactor to some of this, including putting into a class structure. I also suggested that the function args be changed to take in a Composition object to the descriptor functions (which would allow for oxidation state parsing without an extra function to get oxidation states from strings). It's cleaner and more reliable than a String. I think @WardLT should review this and make sure that if I merge this it's not going to mess up what he's been working on.

**Comment by matk86** [comment]
ok

**Comment by WardLT** [comment]
Hello @matk86 and @computron,

Sorry for the delay in replying to this pull request.

At this stage, I wouldn't worry too much about making changes that could affect our refactoring. @JFChen3 and I are expecting to have some merging work to do. That said, adjusting the 'featurizing' functions to take Composition objects as inputs does align with our class model. 

@matk86 Are you in the process of making more changes? If so, I can work towards pushing our changes into the main branch sooner.

Overall, I do not have any objections to this merge.

Thanks!
Logan

**Comment by matk86** [comment]
i stopped working on it when computron mentioned that you are guys are working on it.  Since im not privy to communications between you and computron, I am still not sure about the refactoring of the overall code structure that you guys are planning to do. Once you guys have merged you work i would be in a better position to further add stuff/refactor.

**Comment by WardLT** [comment]
Makes sense. I'll let you know when we have the new refactor working.

To bring you up-to-speed: The portion we're working on now is converting the functions that compute composition-based features into a class-based pattern similar to that of [deepchem](https://github.com/deepchem/deepchem) and Magpie.

**Comment by matk86** [comment]
i see. i will look into it. thanks

**Comment by computron** [comment]
Ok I am just going to pull these changes then. @WardLT would need to address any merge commits (sorry). Thanks both for the quick response

**Comment by computron** [comment]
Actually nevermind I can't pull until conflicts are resolved. So @matk86 if you still want the merge pulled please resolve the conflicts and I'll do it. If not you can close the PR

**Comment by matk86** [comment]
fixed the merge conflicts

**Comment by matk86** [comment]
@WardLT do you guys plan to make the PR soon? If not i would like to give it a try(i'm interested in using some of the stuff in structure feature, so might as well reafctor and clean it up). Let me know

**Comment by computron** [comment]
Hi @matk86 - I am not sure of their schedule. Here were my comments to them regarding the Deepchem class structure:

"I'd certainly be open to going with a class-based structure as I see it's advantages. For example, we could generate a list of all available features by introspecting the code for every class that subclasses the base feature class.

I looked at DeepChem and there were a few things I didn't like about their implementation:
- their "_featurize" function is private(?) - i.e, starts with an underscore. I think it's completely OK and preferable for that method to be public (no underscore). Conversely, some of their more "internal" methods to the class seem to be marked as public but might be clearer as private.
- there is just a lot of documentation "fluff". For example, the documentation for parameters for "_featurize" is duplicated in every single feature implementation. That's just extra space and typing. Similarly, the "MolecularWeight" feature in basic.py tells you twice what it does - once in the initialization, once in the _featurize method. Again, let's just keep the description there once (e.g., in the initialize). I'm all for documentation, but hate repetitiveness and fluff.

These are of course minor concerns and otherwise it looks generally OK to me. There are some bells and whistles I'd add - like having the base "featurize" function for featurizing lots of molecules work with multiprocessing. But again, these are minor.

The only other concern I'd have is performance. I expect we'll be running the feature calls tens of millions of times - e.g., 100,000 data points * 100 features. Thus even small differences in performance (say a hundredth of a second) translate to over a day in difference in featurizing the data set. So some minimal test of performance would be another concern."

**Comment by matk86** [comment]
i went through deepchem and i share the same concerns. Regarding performance: is the goal to cythonize the whole descriptors?

**Comment by WardLT** [comment]
@matk86 We're still a bit away from making a PR. We have some work to do in cleaning up the code (e.g., writing documentation) and making our refactor compatible with the rest of matminer. For example, all of the example notebooks are currently broken.

That said, we are far enough that it is probably worth getting your feedback and for you to use the base class for refactoring the structural features.

@computron Should we create a new branch on this repository for the version with class-based feature calculators? Or, would it be better for us to use @JFChen3's fork for now?

**Comment by matk86** [comment]
another branch sounds good, i can work on that too..

**Comment by WardLT** [comment]
Awesome. I just created a branch "featurizer_refactor" (Sorry, I didn't realize who had what permissions to do that and thought it was only Anubhav some reason). 

@JFChen3 and I will add some quick documentation and issue a PR to this branch sometime soon.

**Comment by matk86** [comment]
great! thnx

**Comment by computron** [comment]
Thanks for coordinating guys, feel free to create/modify things as needed to be productive

**Pull request merged**
