### PR TITLE
Started changing implementors and citations functions so that they always return a tuple.

### PR DESCRIPTION
**Pull request by nisse3000**
@computron and @WardLT, should I continue like that?

### CODE REVIEW

**Comment by computron** [comment]
What's the reason for tuple?

My main gripe with tuples is that one-element tuples can be a "gotcha" that leads to errors.

e.g. if you write
citations = ("my_paper")
it doesn't work since it becomes a string. you need to do citations = ("my_paper", ) with the comma which people often forget

**Comment by nisse3000** [comment]
I've seen that @WardLT uses 1-element tuples and figured I follow his lead.  The nice thing about tuples in the context of implementors and citations is that they are, in fact, immutable.  Thought that would be neatly underscored by using tuples over lists.  But my personal main goal is to increase consistency after having found consensus, which this is all about.

**Comment by computron** [comment]
I don’t understand the advantage of immutability here. Eg one might want to
build up a list of citations based on the parameters that were set (eg a
base citation to start and appending one or more citations if certain flags
were set in the featurizer). Its easier to write this code with mutable
objects since you can use if/else statements to build up a citation list.

Similarly one might want to start with the citation list for the first
featurizer and keep extending the list with the citations of subsequent
featurizer which is a bit easier if you return as list.

So I guess I dont understand why immutability is desired here?

(I agree it should be consistent)

**Comment by WardLT** [comment]
@nisse3000 Thanks for noticing this inconsistancy.

Good question about lists or tuples are better.

I actually didn't have much of a rationale for choosing to use tuples. Immutability does make sense for lists of people who wrote an operation, but we don't have much need for that in the software. 

After some more thought, I'm sold by @computron's argument that the mutability of lists allowing for easier modification (e.g., if the implementors changes depending on parameters). 

In that case, my vote is to actually use set. We would loose the order, but I do not view that as too important. Sound reasonable?

**Comment by nisse3000** [comment]
@computron, the first issue is not that bad because the only thing we do (e.g., in CoordinationNumber) is to "return tuple(citation_list)".  Similarly, adding 2 tuples to a new 3 tuple as the composite tuple with "+" works just fine, right?

But, again, I've only started that because I saw that @WardLT did that here and there and thought that there might be a fundamental rationale that I don't see.  Apparently, that's not the case and I just wanna know how we wanna proceed.  I guess the vote went to using lists.

Since we all like consistency, if you don't merge but close this PR, then I know what I gotta do.  :-)

**Comment by computron** [comment]
>> the first issue is not that bad because the only thing we do (e.g., in CoordinationNumber) is to "return tuple(citation_list)

yes, but why make it awkward and force the developer to make that conversion? Unless there is some real benefit to having it be a tuple at the end of the day.

>> Similarly, adding 2 tuples to a new composite tuple with "+" works just fine, right?

Yes, you could also keep redefining your original tuple. e.g.,

```
x = ("citation1",)
if something:
    x += ("citation2",)
return x
```

But this is not as natural as extending lists which are meant to be mutable. Also, I know this seems like a small thing, but the need for a comma for single-element tuples is actually pretty annoying. I know I've fixed the missing comma for other people's functions in matminer before (can't locate the commit though) because they forgot it.

>> I guess the vote went to using lists.

Well not really. Logan voted to use sets. I am not sure. When collecting together lots of citations and implementors from a bunch of different featurizers, I don't think the order really matters anymore so sets are fine. But for a single featurizer, I think it's nice to retain an ordering to the implementors and maybe even the citations. e.g., for the MiedemaFeaturizer, Alireza helped implement a little bit but Qi is really the "boss". So I think it's nice if Qi's name can always come first so people know she is the main contact.

**Comment by WardLT** [comment]
I agree with @computron's point about the advantage of keeping order.

In that case, I change my vote to "list" because it is easier to modify.


On Jan 23, 2018 5:54 PM, "Anubhav Jain" <notifications@github.com> wrote:

the first issue is not that bad because the only thing we do (e.g., in
CoordinationNumber) is to "return tuple(citation_list)

yes, but why make it awkward and force the developer to make that
conversion? Unless there is some real benefit to having it be a tuple at
the end of the day.

Similarly, adding 2 tuples to a new composite tuple with "+" works just
fine, right?

Yes, you could also keep redefining your original tuple. e.g.,

x = ("citation1",)
if something:
    x += ("citation2",)
return x

But this is not as natural as extending lists which are meant to be
mutable. Also, I know this seems like a small thing, but the need for a
comma for single-element tuples is actually pretty annoying. I know I've
fixed the missing comma for other people's functions in matminer before
(can't locate the commit though) because they forgot it.

I guess the vote went to using lists.

Well not really. Logan voted to use sets. I am not sure. When collecting
together lots of citations and implementors from a bunch of different
featurizers, I don't think the order really matters anymore so sets are
fine. But for a single featurizer, I think it's nice to retain an ordering
to the implementors and maybe even the citations. e.g., for the
MiedemaFeaturizer, Alireza helped implement a little bit but Qi is really
the "boss". So I think it's nice if Qi's name can always come first so
people know she is the main contact.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hackingmaterials/matminer/pull/115#issuecomment-359972686>,
or mute the thread

**Comment by computron** [comment]
Ok so we have a decision - everything is going to be lists!

I will close the current PR, but feel free to start a new one with everything consistent as lists

**Pull request closed without merging**
