### PR TITLE
Automated dependency upgrades

### PR DESCRIPTION
**Pull request by tschaume**
Full log: https://github.com/hackingmaterials/matminer/actions/runs/6143614014

### CODE REVIEW

**Comment by ardunn** [comment]
@tschaume is this the result of an automated workflow or did you open this PR manually? I'm still a bit out of the loop on how the new dependencies manager works, even after reading through the new workflow yaml in .github...

**Comment by ml-evs** [comment]
I believe this is automatic, but currently uses @tschaume's GitHub PAT to make the PR. I don't know why tests don't run automatically for these PRs.

Just to add that there are still outstanding issues from the last dep upgrade where some featurizers are no longer consistent/stable (RDFs are all NaNs, for example): https://github.com/hackingmaterials/matminer/pull/910#issuecomment-1714160466 I fixed most things in https://github.com/hackingmaterials/matminer/pull/912 but cannot spend any more time on this myself at the moment.

**Comment by tschaume** [comment]
@ardunn yes, these PRs are created automatically to keep the requirements files up-to-date. `pip-tools` is used to create requirements files that contain the latest conflict-free versions of all the dependencies. The tests should then run on these PRs (and did for #886) in order to see if there any issues caused by upgrading the dependencies. This approach originated in #880 where I also added a link with more info about the process. HTH.

**Comment by ml-evs** [comment]
I think GH actions won't run tests on PRs that end with commits from people without GH accounts (see blank details on requirements commits above). I don't have admin powers to update this to use my token/committer details. I'm going to extract these changes into a fresh PR.

**Pull request closed without merging**
